# Generated by Django 4.2.2 on 2023-09-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='image_link',
        ),
        migrations.AddField(
            model_name='items',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='card_image/'),
        ),
    ]
