# Generated by Django 4.2.2 on 2023-09-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_remove_items_image_link_items_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='image',
        ),
        migrations.AddField(
            model_name='items',
            name='image_link',
            field=models.TextField(default=''),
        ),
    ]
